name: Run critical Python tests
on:
   - push

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-18.04]
        flask-version: [latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Force the chosen flask version
        run: pip install flask==${{ matrix.flask-version }}
      - name: Test package
        run: poetry run test
      - name: Test package
        run: poetry run doctest
