name: Run full set of Python tests
on:
   - pull_request

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-18.04, macos-latest, windows-latest]
        flask-version: ["1.0", 1.1, "2.0", latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Force the chosen flask version
        run: pip install flask==${{ matrix.flask-version }}
      - name: Run unit tests
        run: poetry run test
      - name: Run doctests
        run: poetry run doctest
